version: '3.7'

services:
  pdns-server:
    image: dockerhub.krypticlabs.com/powerdns/pdns-server
    hostname: ${PDNS_HOST}
    container_name: ${PDNS_HOST}
    networks:
      default_net:
        ipv4_address: ${PDNS_IP}
    expose:
      - '53'
      - '53/udp'
    environment:
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=${PDNS_WEBSERVER_ALLOW_FROM}
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_soa_minimum_ttl=1200
      - PDNS_default_soa_name=ns1.ramstone.net
      - PDNS_default_soa_mail=hostmaster.ramstone.net


  pdns-recursor:
    image: dockerhub.krypticlabs.com/powerdns/pdns-recursor
    hostname: ${PDNS_RECURSOR_HOST}
    container_name: ${PDNS_RECURSOR_HOST}
    networks:
       - default_net
    ports:
      - "192.168.1.45:53:53/tcp"
      - "192.168.1.45:53:53/udp"
    environment:
      - PDNS_forward-zones=ramstone.net=${PDNS_IP}
      - PDNS_allow-from=192.168.0.0/23
      - PDNS_max-negative-ttl=30
      - PDNS_max-cache-ttl=300
    depends_on:
      - pdns-server

  pdns-admin:
    image: dockerhub.krypticlabs.com/powerdns/pdns-admin
    container_name: pdns-admin
    networks:
       - default_net
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False
    depends_on:
      - pdns-server

networks:
  default_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/29
